import { test, expect } from '../../fixtures/app.runner.js';
import {
  LoginPage,
  VaultSelectPage,
  MainPage,
  SideMenuPage,
  CreateOrEditPage,
  Utilities,
  DetailsPage
} from '../../components/index.js';
import testData from '../../fixtures/test-data.js';

test.describe('Password', () => {
  test.describe.configure({ mode: 'serial' })

  let loginPage, vaultSelectPage, createOrEditPage, sideMenuPage, mainPage, utilities, detailsPage, page

  test.beforeAll(async ({ app }) => {
    page = app.page
    loginPage = new LoginPage(page.locator('body'))
    vaultSelectPage = new VaultSelectPage(page.locator('body'))
    mainPage = new MainPage(page.locator('body'))
    sideMenuPage = new SideMenuPage(page.locator('body'))
    createOrEditPage = new CreateOrEditPage(page.locator('body'))
    utilities = new Utilities(page.locator('body'))
    detailsPage = new DetailsPage(page.locator('body'))
  })

  test.beforeEach(async ({ app }) => {
    await loginPage.loginToApplication(testData.credentials.validPassword)
    await vaultSelectPage.selectVaultbyName(testData.vault.name)
  })

  test.afterAll(async ({ }) => {
    await utilities.deleteAllElements()
    await sideMenuPage.clickSidebarExitButton()
  })

  test('Password fields value generated by the app is inserted into "Password" field', async ({ page }) => {

    await test.step('CREATE LOGIN ELEMENT - initial empty element collection', async () => {
      await sideMenuPage.selectSideBarCategory('login')
      await utilities.deleteAllElements()
      await mainPage.clickCreateNewElementButton('Create a login')

      await createOrEditPage.fillCreateOrEditInput('title', 'Login Title')

      await createOrEditPage.fillCreateOrEditInput('username', 'Test User')
      await createOrEditPage.fillCreateOrEditInput('password', 'Test Pass')
      await createOrEditPage.fillCreateOrEditInput('website', 'https://www.website.co')
      await createOrEditPage.fillCreateOrEditInput('note', 'Test Note')

      await createOrEditPage.clickOnCreateOrEditButton('save')
      await page.waitForTimeout(testData.timeouts.action)

    })

    await test.step('OPEN ELEMENT', async () => {
      await mainPage.openElementDetails()
    })

    await test.step('EDIT ELEMENT DETAILS', async () => {
      await detailsPage.editElement()
    })

    /**
   * @qase.id PAS-566
   * @description Password fields value generated by the app is inserted into "Password" field after clicking on "Insert password" button
   */
    await test.step('OPEN PASSWORD MENU', async () => {
      await createOrEditPage.openPasswordMenu()
    })

    await test.step('CLICK INSERT PASSWORD BUTTON FROM PASSWORD MENU', async () => {
      await createOrEditPage.clickInsertPasswordButton()
    })

    await test.step('SHOW PASSWORD AND VERIFY PASSWORD VALUE HAS CHANGED', async () => {
      await createOrEditPage.clickShowHidePasswordButtonLast()
      await createOrEditPage.verifyPasswordToNotHaveValue('Test Password')
    })

    await test.step('CLICK CLOSE (X) BUTTON', async () => {
      await createOrEditPage.clickElementItemCloseButton()

    })

  })

  // ### This test will be uncomment after adding selector id's ###

  // test('Password menu verification', async ({ page }) => {

  //   await test.step('LOGIN', async () => {
  //     await expect(loginPage.title).toHaveText('Enter your Master password')
  //     await loginPage.login(testData.credentials.validPassword)
  //   })

  //   await test.step('VAULT SELECTION', async () => {
  //     await expect(vaultSelectPage.title).toHaveText('Select a vault, create a new one or load another one')
  //     await vaultSelectPage.selectVault(testData.vault.name)
  //   })

  //   await test.step('OPEN LOGIN ELEMENT AND VERIFY PASSWORD MENU OPTIONS', async () => {
  //     await mainView.openElementDetails()
  //     await mainView.editElement()
  //     await createLoginPage.openPasswordMenu()
  //     await createLoginPage.verifyPasswordTypeRadioButtonState('active')
  //     await createLoginPage.verifyPassphraseTypeRadioButtonState('inactive')
  //     await createLoginPage.verifyCharSliderIsVisible()
  //     await createLoginPage.verifyspecialCharacterSwitcherState('on')

  //   })

  //   await test.step('Exit to login screen', async () => {
  //     await createLoginPage.clickElementItemCloseButton()
  //   })

  //   await test.step('Exit to login screen', async () => {
  //     await createLoginPage.clickElementItemCloseButton()
  //   })

  // await test.step('Exit to login screen', async () => {
  //   await mainView.clickSidebarExitButton()
  // })

  // })

})
